# Generated by Django 5.1.7 on 2025-04-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0003_habit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
