# Generated by Django 5.1.7 on 2025-04-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0004_habit_current_streak_habit_last_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=20),
        ),
    ]
