# Generated by Django 5.1.7 on 2025-04-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0005_habit_closed_at_habit_completed_alter_habit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
