# Generated by Django 5.1.7 on 2025-04-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0006_habit_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='last_completed_date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='longest_streak',
        ),
    ]
