# Generated by Django 5.1.7 on 2025-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.CharField(default="It's time!", max_length=255),
        ),
    ]
