# Generated by Django 5.1.7 on 2025-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitanalytics',
            name='average_completion_time',
        ),
        migrations.AddField(
            model_name='habitanalytics',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitanalytics',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitanalytics',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
